/**
 * Generates src/styles/caffeine.css from the tweakcn "caffeine" theme.
 *
 *   bun run tokens            # regenerate from the vendored copy
 *   bun run tokens --fetch    # refresh the vendored copy from tweakcn first
 *
 * caffeine.json is `"type": "registry:style"` — design tokens only, no component
 * code — so the tokens are ported directly instead of running the official
 * shadcn CLI, which would scaffold React + Tailwind into a Svelte + UnoCSS repo.
 *
 * The generated stylesheet is committed on purpose. Fetching tweakcn during a
 * build would let a third party change our colours between deploys.
 */

import { writeFile } from "node:fs/promises";
import { join } from "node:path";

const THEME_URL = "https://tweakcn.com/r/themes/caffeine.json";
const VENDORED = join(import.meta.dir, "..", "src", "styles", "caffeine.theme.json");
const OUTPUT = join(import.meta.dir, "..", "src", "styles", "caffeine.css");

interface RegistryStyle {
  name: string;
  type: string;
  cssVars: {
    theme?: Record<string, string>;
    light?: Record<string, string>;
    dark?: Record<string, string>;
  };
}

async function loadTheme(): Promise<RegistryStyle> {
  if (process.argv.includes("--fetch")) {
    const response = await fetch(THEME_URL);
    if (!response.ok) throw new Error(`Could not fetch ${THEME_URL}: ${response.status}`);
    const json = (await response.json()) as RegistryStyle;
    await writeFile(VENDORED, `${JSON.stringify(json, null, 2)}\n`, "utf8");
    console.log(`Refreshed ${VENDORED}`);
    return json;
  }
  return (await Bun.file(VENDORED).json()) as RegistryStyle;
}

function renderBlock(
  selector: string,
  vars: Record<string, string>,
  colorScheme: string,
): string {
  const declarations = Object.entries(vars)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join("\n");
  return `${selector} {\n  color-scheme: ${colorScheme};\n${declarations}\n}\n`;
}

const theme = await loadTheme();
if (theme.type !== "registry:style") {
  throw new Error(`Expected a registry:style theme, got "${theme.type}".`);
}

const { theme: base = {}, light = {}, dark = {} } = theme.cssVars;

const header = `/**
 * Design tokens ported from the tweakcn "${theme.name}" theme.
 *
 * Source: ${THEME_URL} ("type": "registry:style" — tokens
 * only, no component code). Committed deliberately: fetching a third party at
 * build time would let them change our colours between deploys.
 *
 * The official shadcn CLI targets React + Tailwind; this stack is Svelte 5 +
 * UnoCSS, so the tokens are ported rather than scaffolded. presetShadcn() in
 * uno.config.ts consumes these variables.
 *
 * Generated by scripts/tokens.ts — DO NOT EDIT BY HAND.
 */
`;

const css = [
  header,
  renderBlock(":root", { ...base, ...light }, "light"),
  renderBlock(".dark", dark, "dark"),
].join("\n");

await writeFile(OUTPUT, css, "utf8");
console.log(
  `Wrote ${OUTPUT} — ${Object.keys(base).length} theme, ${Object.keys(light).length} light, ${Object.keys(dark).length} dark vars.`,
);
